### ISSUE TITLE
Excercise 3: "CustomersRemote" is either 'abstract' or '@cds.persistence.skip'

### ISSUE THREAD

**Issue by mjhcorporate** [SAP-samples/cloud-sample-spaceflight-java#2] opened 2019-07-04 12:46 UTC
In Exercise 03, after uncommenting the appropriate code blocks (as described in the tutorial and in the OpenSAP course) I still cannot successfully execute "Build CDS". I get a wall of errors, starting with 

```
2:42:14 PM (Executor) This is CDS 3.13.0, Compiler 1.15.0, Home: node_modules/@sap/cds
2:42:14 PM (Executor) 
2:42:15 PM (Executor) [ERROR] db/index.cds:26:35-50: "teched.flight.trip.Customers": "teched.flight.trip.CustomersRemote" in path step "CustomersRemote" of "CustomersRemote" is either 'abstract' or '@cds.persistence.skip'
2:42:15 PM (Executor) npm ERR! code ELIFECYCLE
...
```

To make sure I did not do any editing mistakes, I additionally tried the branch "s4bp-final", but got the same error.

**Comment by chgeo** [comment] 2019-07-04 16:47
Thanks for reporting.  This seems to be a regression in the latest cds compiler.  I will forward this to the team.

As a workaround, in top-level `package.json` change the version of `@sap/cds` to `3.10.0`.  This should bring you back to a safe state.

**Comment by chgeo** [comment] 2019-07-08 11:32
Will be fixed with the next CDS version.  In the meantime I will lock down the version to 3.10.0 on Github.

**Closed** 2020-05-26 14:21 UTC
